name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        node_version: [ 18, 19 ]

    runs-on: ${{ matrix.os }}

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js v${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm i
      - run: npm i -g .
      - run: fast-directory-size .
      - run: npm test
